### PR TITLE
Using time.Ticker for running stoppable listener. Fix edge case where flush happens after the listener is stopped.

### LINKED ISSUE #18: Need a way to wait progress bar output its final state
```
package main

import (
    "time"

    "github.com/gosuri/uiprogress"
)

func main() {
    uiprogress.Start()            // start rendering
    bar := uiprogress.AddBar(100) // Add a new bar

    // optionally, append and prepend completion and elapsed time
    bar.AppendCompleted()
    bar.PrependElapsed()

    for bar.Incr() {
        time.Sleep(time.Millisecond * 1)
    }
}
```

If you reduce sleep time (less than `uiprogress.RefreshInterval`), the progress bar will not reach 100%, see:

```
$ go run example/simple/simple.go 
    0 [=================================================================>--]  97%
```

I think there should have a mechanism to make sure the outputs are consistent. A `Flush()` method?

For example:

```
for bar.Incr() {
    time.Sleep(time.Millisecond * 1)
}
uiprogress.Flush()
```

### PR DESCRIPTION
**Pull request by henvic**
This should close #18 and #20.

@mgurov, can you take a look at the changes I have made on top of your code (which I actually rebased), please?

https://github.com/gosuri/uilive/pull/7 is also needed.

### CODE REVIEW

File: progress.go [hunk 1]
```diff
@@ -86,34 +85,41 @@ func (p *Progress) AddBar(total int) *Bar {
...
 func (p *Progress) Listen() {
 	p.lw.Out = p.Out
-	for {
-		select {
-		case <-p.stopChan:
-			return
-		default:
-			time.Sleep(p.RefreshInterval)
+
+	go func() {
```
Comment (mgurov) [inline progress.go]: exported function `.Listen()` changes its behavior from doing the listen loop to spawning a goroutine and exiting without waiting for the end of the processing. Which is a breaking change, IMHO and should probably be avoided.

File: progress.go [hunk 2]
```diff
@@ -86,34 +85,41 @@ func (p *Progress) AddBar(total int) *Bar {
...
+		for _ = range p.ticker.C {
```
Comment (mgurov) [inline progress.go]: [ticker.Stop](https://golang.org/pkg/time/#Ticker.Stop) doesn't close the tick chan, which means this goroutine will never exit and cause a leak. This is easy to check by adding a log/panic statement between lines 65/96.

File: progress.go [hunk 3]
```diff
@@ -86,34 +85,41 @@ func (p *Progress) AddBar(total int) *Bar {
...
 	}
+	p.mtx.Unlock()
+
 	go p.Listen()
 }
 
 // Stop stops listening
 func (p *Progress) Stop() {
-	close(p.stopChan)
-	p.stopChan = nil
```
Comment (mgurov) [inline progress.go:116]: This line would allow earlier to restart the listener. Suggested implementation doesn't support this anymore. Not saying whether this is important or not, just a word of caution.

**Comment by mgurov** [comment]
@henvic works for me from the functional point of view.

**Comment by henvic** [comment]
@mgurov, what about now? I have done the same changes on uilive as well.

**Comment by mgurov** [comment]
@henvic LGTM now. My comments are addressed. Thank you!

**Comment by henvic** [comment]
Hey @mgurov,

If you run the tests repeatedly (just do `while true; do go test; done`) you will see they fail from time to time (even though my examples are running flawlessly).

I have tried adding even a `time.Sleep(2 * p.RefreshInterval)` on the Stop() of uiprogress and uilive just after close(), but it doesn't do any difference. Any ideas of what may be going on? Thanks.

**Comment by mgurov** [comment]
@henvic two things. 

First, if you run `make test` repeatedly you'll soon hit race conditions because the newly added test uses unsynchronized `bytes.Buffer` for progress and for `fmt.Fprintf(buffer, "foo")`. Adding some form of  [synchronization](http://stackoverflow.com/a/36226525/243861) would help. 

Second, as far as I can see there is no strict guarantee that your `fmt.Fprintf(buffer, "foo")` will happen _after_ the last flush at the `case <-p.ticker.C` of the `Listener()`. Say the signal from the ticker arrived at the same moment `Stop()` has just acquired the write lock. Ticker handling will proceed after the `Stop()` is done, on a collision course with the `fmt.Fprintf`, occasionally leading to a suffix different than you expect in the test.

**Comment by henvic** [comment]
@mgurov,
why would you hit race conditions given that `while true; do go test; done` runs several, independent processes, and in series (as in, each one after the previous exited)? It doesn't make sense for me.

Actually note that this might happen even for just one test. I said to run it repeatedly because it'd be easier for the issue to be replicated.

**Comment by henvic** [comment]
I think with these last changes the synchronization issue is gone.

**Comment by xorpaul** [comment]
:+1: for merge

**Comment by henvic** [comment]
@xorpaul, if you are blocked while these fixes doesn't make mainstream you can temporarily use my fork (or better, do a fork of this repo yourself and do what I did in order for you to keep track you're not using the official version). It is set with the fix-race-condition-on-stop-henvic branch as the default one and the uilive dependency there is pointing to a uilive with these fixes as well, so you can just 'go get' and use it (or do the same for uilive). Just need to replace gosuri with henvic on your code.

**Comment by xorpaul** [comment]
@henvic Yeah, thanks for the suggestion, but I am already using your fork :smile:

**Comment by gosuri** [comment]
great! thanks so much
